name     = "accents"
summary  = "Type accented characters with AltGr"
version  = "0.1.0"
category = "Hardware"
tags     = ["hyprland","keyboard"]
author   = "pehcastro"
kind     = "hypr"
needs    = []
keys     = []
